feat: check rust linting on ci
Signed-off-by: Norman Meier <norman@samourai.coop>

diff --git a/.github/workflows/rust.yml b/.github/workflows/rust.yml
--- a/.github/workflows/rust.yml
+++ b/.github/workflows/rust.yml
@@ -21,5 +21,15 @@ jobs:
       - name: Test
         run: make test.rust
 
-      - name: Check diff
-        run: git diff --exit-code
+      - name: Lint
+        run: make lint-fix.rust
+
+      - name: Check that there is no diff
+        run: |
+          mrdiff=$(git status --porcelain)
+          if [[ $mrdiff ]]; then
+              echo 'ERROR: Diff found!'
+              echo $mrdiff
+              git diff
+              exit 1
+          fi
